apps:
  dade:
    command: 'bin/dade'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/dade/issues'
description: 'Extract and convert assets from a collection of PC and console video games.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/dade/issues'
license: 'MIT'
name: 'dade'
parts:
  dade:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/dade'
summary: 'Extract and convert assets from a collection of PC and console video games.'
title: 'dade'
version: '0.0.2'
website: 'https://tatsh.github.io/dade/'
